### ISSUE TITLE
Audio Invert L&R

### ISSUE THREAD

**Issue by Sebaister** [zls84/win-wasapi-ms2109#1]
hello first of all I apologize if it is not the right method for this, a long time ago I was looking for a plugin to solve only this problem of generic HDMI capture devices, getting to the point the plugins work great for me, but for some reason I hear myself reversed, for example, the Mario karts when passing on my right I hear them pass on my left,   I suggest that in the plugin properties add an option to invert the L and R channels

**Comment by zls84** [comment]
Are the channels swapped always or just sometimes?

**Comment by Sebaister** [comment]
It always happens to me, curiously when I use the mono-to-stereo.exe program from ToadKing both channels sound fine but it is not an obs plugin

**Comment by zls84** [comment]
I know mono-to-stereo.exe. That's what I wanted to ask, but I got the answer.

My first idea was to make this plugin based on mono-to-stereo. However, in the meantime it seemed that it was also functional. (On my tests, the channels were good with my capture card. I have 2 MS2109-based cards, but they are the same type. I was also afraid that there might be channel swapping.)

I'm currently on 3 weeks vacation, but as soon as I get home (tomorow), I'll try to do the channel swap as a quick fix. Later on, I will review what mono-to-stereo does and implement it based on that.

(I have other plans as well, but for those, I currently see that an expensive certificate would be required, which unfortunately is not worth it. It would rather be a unique driver, so it could be used with any program, e.g.: OBS, StreamLabs OBS, etc...)

**Comment by zls84** [comment]
Hi @Sebaister !

Sorry, I was a little busy since last week. But today the channel swap is done.
The option is in "Audio Input Capture (MS2109 support)" properties.
I hope this can solve the issue.

https://github.com/zls84/win-wasapi-ms2109/releases/tag/1.0.1

**Comment by Sebaister** [comment]
Great job, works perfectly
